//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace diosmio.Models
{
    public class Empleados
    {
        public int idEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Dni { get; set; }
        public string Distrito { get; set; }
        public string Direccion { get; set; }
        public decimal Sueldo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}